---
dependency:
  name: galaxy
  options:
    role-file: '${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml'
    requirements-file: '${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml'
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
# platforms:
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: yes
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - lint
    - syntax
    # - create
    # - converge
    # - idempotence
    # - verify
    # - destroy
